services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: python-demo
    env: python
    plan: free
    rootDir: services/python-demo
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app


  - type: web
    name: frontend
    env: static
    plan: free
    rootDir: frontend
    staticPublishPath: ./
