services:
  - type: web
    name: backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: python-demo
    env: python
    plan: free
    rootDir: services/python-demo
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: web
    name: phase-vocoder
    env: python
    plan: free
    rootDir: services/phase-vocoder-speech
    buildCommand: ./render_build.sh
    startCommand: cd backend && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: frontend
    env: static
    rootDir: frontend
    staticPublishPath: ./
